# Class names of the dataset (order matters)
class_names: ["Background",
                      "BaseballPitch",
                      "BasketballDunk",
                      "Billiards",
                      "CleanAndJerk",
                      "CliffDiving",
                      "CricketBowling",
                      "CricketShot",
                      "Diving",
                      "FrisbeeCatch",
                      "GolfSwing",
                      "HammerThrow",
                      "HighJump",
                      "JavelinThrow",
                      "LongJump",
                      "PoleVault",
                      "Shotput",
                      "SoccerPenalty",
                      "TennisSwing",
                      "ThrowDiscus",
                      "VolleyballSpiking",
                      "Ambiguous"
                      ]
# Class names to exclude from the evaluation
exclude_classes: ["Background", "Ambiguous"]
fps: 4

# temporal offset thresholds (in seconds). Used only for single test
tOffset_thresholds: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

# Parameters for the quasi-online action detection module. Used only for single test
detection_params:
  window_size: 12
  inhibition_time: 0
  sigma: 1
  min_dist: 8